name: Build luac-parser

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: aarch64-unknown-linux-gnu

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build for aarch64
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: luac-aarch64
          path: target/aarch64-unknown-linux-gnu/release/luac-parser
