name: Build luac-parser

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: luac-parser
          path: target/wasm32-unknown-unknown/release/
